package com.abugray.menu;

import com.abugray.conect.DatabaseConnection;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author abu
 */
public final class component extends javax.swing.JPanel {

    private ResultSet rs;
    private Statement st;
    ImageIcon info, error;
    private final Connection koneksi;
    
    public component() {
        initComponents();
        info = new ImageIcon("src/com/abugray/icon/dlg-info.png");
        error = new ImageIcon("src/com/abugray/icon/dlg-error.png");
        koneksi = DatabaseConnection.getConnection("localhost", "3306", "root", "", "ipk");
        Menu.countMI.setEnabled(true);
        Menu.countTB.setEnabled(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mk1 = new javax.swing.JTextField();
        mk2 = new javax.swing.JTextField();
        mk3 = new javax.swing.JTextField();
        mk4 = new javax.swing.JTextField();
        mk5 = new javax.swing.JTextField();
        mk6 = new javax.swing.JTextField();
        mk7 = new javax.swing.JTextField();
        mk8 = new javax.swing.JTextField();
        mk9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        sks = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        nilai1TF = new javax.swing.JTextField();
        nilai2TF = new javax.swing.JTextField();
        nilai3TF = new javax.swing.JTextField();
        nilai4TF = new javax.swing.JTextField();
        nilai5TF = new javax.swing.JTextField();
        nilai6TF = new javax.swing.JTextField();
        nilai7TF = new javax.swing.JTextField();
        nilai8TF = new javax.swing.JTextField();
        nilai9TF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        sks1TF = new javax.swing.JTextField();
        sks2TF = new javax.swing.JTextField();
        sks3TF = new javax.swing.JTextField();
        sks4TF = new javax.swing.JTextField();
        sks5TF = new javax.swing.JTextField();
        sks6TF = new javax.swing.JTextField();
        sks7TF = new javax.swing.JTextField();
        sks8TF = new javax.swing.JTextField();
        sks9TF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        nk = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        nk1 = new javax.swing.JTextField();
        nk5 = new javax.swing.JTextField();
        nk2 = new javax.swing.JTextField();
        nk4 = new javax.swing.JTextField();
        nk8 = new javax.swing.JTextField();
        nk3 = new javax.swing.JTextField();
        nk7 = new javax.swing.JTextField();
        nk6 = new javax.swing.JTextField();
        nk9 = new javax.swing.JTextField();
        smesterCB = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        ips = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        ipk = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        hitungL = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mata Kuliah");

        mk1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk1.setForeground(new java.awt.Color(0, 0, 0));
        mk1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk1.setOpaque(false);

        mk2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk2.setForeground(new java.awt.Color(0, 0, 0));
        mk2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk2.setOpaque(false);
        mk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mk2ActionPerformed(evt);
            }
        });

        mk3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk3.setForeground(new java.awt.Color(0, 0, 0));
        mk3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk3.setOpaque(false);

        mk4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk4.setForeground(new java.awt.Color(0, 0, 0));
        mk4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk4.setOpaque(false);

        mk5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk5.setForeground(new java.awt.Color(0, 0, 0));
        mk5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk5.setOpaque(false);

        mk6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk6.setForeground(new java.awt.Color(0, 0, 0));
        mk6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk6.setOpaque(false);

        mk7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk7.setForeground(new java.awt.Color(0, 0, 0));
        mk7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk7.setOpaque(false);

        mk8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk8.setForeground(new java.awt.Color(0, 0, 0));
        mk8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk8.setOpaque(false);

        mk9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        mk9.setForeground(new java.awt.Color(0, 0, 0));
        mk9.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        mk9.setOpaque(false);

        jLabel2.setText("1");

        jLabel3.setText("2");

        jLabel4.setText("3");

        jLabel5.setText("4");

        jLabel6.setText("5");

        jLabel7.setText("6");

        jLabel8.setText("7");

        jLabel9.setText("8");

        jLabel20.setText("9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mk1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(mk2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mk9, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mk9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(102, 102, 102));

        sks.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        sks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sks.setText("0");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel11.setText("SKS");

        jPanel5.setBackground(new java.awt.Color(153, 153, 153));

        nilai1TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai1TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai1TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai1TF.setOpaque(false);
        nilai1TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai1TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai2TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai2TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai2TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai2TF.setOpaque(false);
        nilai2TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai2TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai3TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai3TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai3TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai3TF.setOpaque(false);
        nilai3TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai3TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai4TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai4TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai4TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai4TF.setOpaque(false);
        nilai4TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai4TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai5TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai5TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai5TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai5TF.setOpaque(false);
        nilai5TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai5TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai6TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai6TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai6TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai6TF.setOpaque(false);
        nilai6TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai6TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai7TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai7TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai7TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai7TF.setOpaque(false);
        nilai7TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai7TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai8TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai8TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai8TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai8TF.setOpaque(false);
        nilai8TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai8TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        nilai9TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nilai9TF.setForeground(new java.awt.Color(255, 0, 0));
        nilai9TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nilai9TF.setOpaque(false);
        nilai9TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nilai9TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keyTipeNilai(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nilai1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai6TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai7TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai8TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nilai9TF, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nilai1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai6TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai7TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai8TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nilai9TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Jumlah");

        jLabel12.setText("Nilai");

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));

        sks1TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks1TF.setForeground(new java.awt.Color(255, 0, 0));
        sks1TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks1TF.setOpaque(false);
        sks1TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks1TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks2TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks2TF.setForeground(new java.awt.Color(255, 0, 0));
        sks2TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks2TF.setOpaque(false);
        sks2TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks2TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks3TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks3TF.setForeground(new java.awt.Color(255, 0, 0));
        sks3TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks3TF.setOpaque(false);
        sks3TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks3TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks4TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks4TF.setForeground(new java.awt.Color(255, 0, 0));
        sks4TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks4TF.setOpaque(false);
        sks4TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks4TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks5TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks5TF.setForeground(new java.awt.Color(255, 0, 0));
        sks5TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks5TF.setOpaque(false);
        sks5TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks5TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks6TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks6TF.setForeground(new java.awt.Color(255, 0, 0));
        sks6TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks6TF.setOpaque(false);
        sks6TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks6TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks7TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks7TF.setForeground(new java.awt.Color(255, 0, 0));
        sks7TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks7TF.setOpaque(false);
        sks7TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks7TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks8TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks8TF.setForeground(new java.awt.Color(255, 0, 0));
        sks8TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks8TF.setOpaque(false);
        sks8TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks8TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        sks9TF.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        sks9TF.setForeground(new java.awt.Color(255, 0, 0));
        sks9TF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sks9TF.setOpaque(false);
        sks9TF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sks9TFKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sks1TFKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sks2TF, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                    .addComponent(sks3TF)
                    .addComponent(sks4TF)
                    .addComponent(sks5TF)
                    .addComponent(sks6TF)
                    .addComponent(sks7TF)
                    .addComponent(sks8TF)
                    .addComponent(sks1TF)
                    .addComponent(sks9TF))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sks1TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks2TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks3TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks4TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks5TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks6TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks7TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks8TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sks9TF, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel13.setText("NxK");

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        nk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nk.setForeground(new java.awt.Color(255, 255, 255));
        nk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nk.setText("0.0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        nk1.setEditable(false);
        nk1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk1.setForeground(new java.awt.Color(0, 0, 0));
        nk1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk1.setOpaque(false);

        nk5.setEditable(false);
        nk5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk5.setForeground(new java.awt.Color(0, 0, 0));
        nk5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk5.setOpaque(false);

        nk2.setEditable(false);
        nk2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk2.setForeground(new java.awt.Color(0, 0, 0));
        nk2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk2.setOpaque(false);
        nk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nk2ActionPerformed(evt);
            }
        });

        nk4.setEditable(false);
        nk4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk4.setForeground(new java.awt.Color(0, 0, 0));
        nk4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk4.setOpaque(false);

        nk8.setEditable(false);
        nk8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk8.setForeground(new java.awt.Color(0, 0, 0));
        nk8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk8.setOpaque(false);

        nk3.setEditable(false);
        nk3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk3.setForeground(new java.awt.Color(0, 0, 0));
        nk3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk3.setOpaque(false);

        nk7.setEditable(false);
        nk7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk7.setForeground(new java.awt.Color(0, 0, 0));
        nk7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk7.setOpaque(false);

        nk6.setEditable(false);
        nk6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk6.setForeground(new java.awt.Color(0, 0, 0));
        nk6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk6.setOpaque(false);

        nk9.setEditable(false);
        nk9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nk9.setForeground(new java.awt.Color(0, 0, 0));
        nk9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nk9.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nk1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nk9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nk1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nk9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        smesterCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilih Smester--", "Smester 1", "Smester 2", "Smester 3", "Smester 4", "Smester 5", "Smester 6", "Smester 7", "Smester 8", " " }));
        smesterCB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));
        smesterCB.setOpaque(false);
        smesterCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smesterCBActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(153, 153, 153));

        ips.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ips.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ips.setText("0");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ips, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ips, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(204, 204, 204));

        ipk.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ipk.setForeground(new java.awt.Color(255, 255, 255));
        ipk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ipk.setText("0.0");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ipk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ipk, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel15.setText("IPS");

        jLabel16.setText("IPK");

        hitungL.setBackground(new java.awt.Color(51, 51, 51));
        hitungL.setForeground(new java.awt.Color(204, 204, 204));
        hitungL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hitungL.setText("Hitung");
        hitungL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        hitungL.setOpaque(true);
        hitungL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hitungLMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hitungLMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hitungLMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hitungL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(smesterCB, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(smesterCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hitungL, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nk2ActionPerformed

    private void mk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mk2ActionPerformed

    private void nilai1TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai1TFKeyReleased
        nk1.setText(setNK(nilai1TF.getText(), sks1TF.getText()));
    }//GEN-LAST:event_nilai1TFKeyReleased

    private void nilai2TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai2TFKeyReleased
        nk2.setText(setNK(nilai2TF.getText(), sks2TF.getText()));
    }//GEN-LAST:event_nilai2TFKeyReleased

    private void nilai3TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai3TFKeyReleased
        nk3.setText(setNK(nilai3TF.getText(), sks3TF.getText()));
    }//GEN-LAST:event_nilai3TFKeyReleased

    private void nilai4TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai4TFKeyReleased
        nk4.setText(setNK(nilai4TF.getText(), sks4TF.getText()));
    }//GEN-LAST:event_nilai4TFKeyReleased

    private void nilai5TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai5TFKeyReleased
        nk5.setText(setNK(nilai5TF.getText(), sks5TF.getText()));
    }//GEN-LAST:event_nilai5TFKeyReleased

    private void nilai6TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai6TFKeyReleased
        nk6.setText(setNK(nilai6TF.getText(), sks6TF.getText()));
    }//GEN-LAST:event_nilai6TFKeyReleased

    private void nilai7TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai7TFKeyReleased
        nk7.setText(setNK(nilai7TF.getText(), sks7TF.getText()));
    }//GEN-LAST:event_nilai7TFKeyReleased

    private void nilai8TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai8TFKeyReleased
        nk8.setText(setNK(nilai8TF.getText(), sks8TF.getText()));
    }//GEN-LAST:event_nilai8TFKeyReleased

    private void nilai9TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nilai9TFKeyReleased
        nk9.setText(setNK(nilai9TF.getText(), sks9TF.getText()));
    }//GEN-LAST:event_nilai9TFKeyReleased

    private void sks1TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks1TFKeyReleased
        nk1.setText(setNK(nilai1TF.getText(), sks1TF.getText()));
    }//GEN-LAST:event_sks1TFKeyReleased

    private void sks2TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks2TFKeyReleased
        nk2.setText(setNK(nilai2TF.getText(), sks2TF.getText()));
    }//GEN-LAST:event_sks2TFKeyReleased

    private void sks3TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks3TFKeyReleased
        nk3.setText(setNK(nilai3TF.getText(), sks3TF.getText()));
    }//GEN-LAST:event_sks3TFKeyReleased

    private void sks4TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks4TFKeyReleased
        nk4.setText(setNK(nilai4TF.getText(), sks4TF.getText()));
    }//GEN-LAST:event_sks4TFKeyReleased

    private void sks5TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks5TFKeyReleased
        nk5.setText(setNK(nilai5TF.getText(), sks5TF.getText()));
    }//GEN-LAST:event_sks5TFKeyReleased

    private void sks6TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks6TFKeyReleased
        nk6.setText(setNK(nilai6TF.getText(), sks6TF.getText()));
    }//GEN-LAST:event_sks6TFKeyReleased

    private void sks7TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks7TFKeyReleased
        nk7.setText(setNK(nilai7TF.getText(), sks7TF.getText()));
    }//GEN-LAST:event_sks7TFKeyReleased

    private void sks8TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks8TFKeyReleased
        nk8.setText(setNK(nilai8TF.getText(), sks8TF.getText()));
    }//GEN-LAST:event_sks8TFKeyReleased

    private void sks9TFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks9TFKeyReleased
        nk9.setText(setNK(nilai9TF.getText(), sks9TF.getText()));
    }//GEN-LAST:event_sks9TFKeyReleased

    private void smesterCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smesterCBActionPerformed
        switch (smesterCB.getSelectedIndex()) {
            case 1:
                Menu.clear();
                show("smester1","t_nilai1");
                break;
            case 2:
                Menu.clear();
                show("smester2","t_nilai2");
                break;
            case 3:
                Menu.clear();
                show("smester3","t_nilai3");
                break;
            case 4:
                Menu.clear();
                show("smester4","t_nilai4");
                break;
            case 5:
                Menu.clear();
                show("smester5","t_nilai5");
                break;
            case 6:
                Menu.clear();
                show("smester6","t_nilai6");
                break;
            case 7:
                Menu.clear();
                show("smester7","t_nilai7");
                break;
            case 8:
                Menu.clear();
                show("smester8","t_nilai8");
                break;
            default:
                Menu.clear();
                break;    
        }
    }//GEN-LAST:event_smesterCBActionPerformed

    private void hitungLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungLMouseClicked
       hitung();
    }//GEN-LAST:event_hitungLMouseClicked

    private void hitungLMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungLMouseEntered
        warna(hitungL, 102,102,102);
    }//GEN-LAST:event_hitungLMouseEntered

    private void hitungLMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hitungLMouseExited
        warna(hitungL, 51,51,51);
    }//GEN-LAST:event_hitungLMouseExited

    private void keyTipeNilai(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyTipeNilai
        char enter = evt.getKeyChar();
        if (Character.isDigit(enter) || enter == KeyEvent.VK_SPACE || enter == KeyEvent.VK_DELETE){ 
            evt.consume();
        }
    }//GEN-LAST:event_keyTipeNilai

    private void sks1TFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sks1TFKeyTyped
        char enter = evt.getKeyChar();
        if (Character.isAlphabetic(enter) || enter == KeyEvent.VK_SPACE || enter == KeyEvent.VK_DELETE){ 
            evt.consume();
        }
    }//GEN-LAST:event_sks1TFKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel hitungL;
    public static javax.swing.JLabel ipk;
    public static javax.swing.JLabel ips;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JTextField mk1;
    public static javax.swing.JTextField mk2;
    public static javax.swing.JTextField mk3;
    public static javax.swing.JTextField mk4;
    public static javax.swing.JTextField mk5;
    public static javax.swing.JTextField mk6;
    public static javax.swing.JTextField mk7;
    public static javax.swing.JTextField mk8;
    public static javax.swing.JTextField mk9;
    public static javax.swing.JTextField nilai1TF;
    public static javax.swing.JTextField nilai2TF;
    public static javax.swing.JTextField nilai3TF;
    public static javax.swing.JTextField nilai4TF;
    public static javax.swing.JTextField nilai5TF;
    public static javax.swing.JTextField nilai6TF;
    public static javax.swing.JTextField nilai7TF;
    public static javax.swing.JTextField nilai8TF;
    public static javax.swing.JTextField nilai9TF;
    public static javax.swing.JLabel nk;
    public static javax.swing.JTextField nk1;
    public static javax.swing.JTextField nk2;
    public static javax.swing.JTextField nk3;
    public static javax.swing.JTextField nk4;
    public static javax.swing.JTextField nk5;
    public static javax.swing.JTextField nk6;
    public static javax.swing.JTextField nk7;
    public static javax.swing.JTextField nk8;
    public static javax.swing.JTextField nk9;
    public static javax.swing.JLabel sks;
    public static javax.swing.JTextField sks1TF;
    public static javax.swing.JTextField sks2TF;
    public static javax.swing.JTextField sks3TF;
    public static javax.swing.JTextField sks4TF;
    public static javax.swing.JTextField sks5TF;
    public static javax.swing.JTextField sks6TF;
    public static javax.swing.JTextField sks7TF;
    public static javax.swing.JTextField sks8TF;
    public static javax.swing.JTextField sks9TF;
    public static javax.swing.JComboBox<String> smesterCB;
    // End of variables declaration//GEN-END:variables

    public double getNilai(String a){
        double nilaiHuruf = 0.0;
        try{
            if(a.equalsIgnoreCase("A")){
                nilaiHuruf = 4.0;
            } else if(a.equalsIgnoreCase("AB")){
                nilaiHuruf = 3.5;
            } else if(a.equalsIgnoreCase("B")){
                nilaiHuruf = 3.0;
            } else if(a.equalsIgnoreCase("BC")){
                nilaiHuruf = 2.5;
            } else if(a.equalsIgnoreCase("C")){
                nilaiHuruf = 2.0;
            } else if(a.equalsIgnoreCase("CD")){
                nilaiHuruf = 1.5;
            } else if(a.equalsIgnoreCase("D")){
                nilaiHuruf = 1.0;
            }else if(a.equalsIgnoreCase("DE")){
                nilaiHuruf = 0.5;
            }else if(a.equalsIgnoreCase("E")){
                nilaiHuruf = 0.0;
            }else {
                nilaiHuruf = 0.0;
            }
        }catch (NumberFormatException e){
        }  
        return nilaiHuruf;
    }
    
    public double hitungNxK(String a, String b){
        double hasil = 0, nilai, s;
        try{
            nilai = getNilai(a);
            s = getSKS(b);
            hasil = nilai*s;
        }catch (NumberFormatException e){
        }
        return hasil;
    }
  
    public int getSKS(String a){
        int besarSks = 0;
        try{
            besarSks = Integer.parseInt(a);
        }catch (NumberFormatException e){
        }
        return besarSks;  
    }
    
    public double  hitungNK(){
        double hasilnk =0, nilai1, nilai2, nilai3, nilai4,nilai5, nilai6,nilai7, nilai8,nilai9, totnk;
        try{
            nilai1 = hitungNxK(nilai1TF.getText(), sks1TF.getText());
            nilai2 = hitungNxK(component.nilai2TF.getText(), sks2TF.getText());
            nilai3 = hitungNxK(nilai3TF.getText(), sks3TF.getText());
            nilai4 = hitungNxK(nilai4TF.getText(), sks4TF.getText());
            nilai5 = hitungNxK(nilai5TF.getText(), sks5TF.getText());
            nilai6 = hitungNxK(nilai6TF.getText(), sks6TF.getText());
            nilai7 = hitungNxK(nilai7TF.getText(), sks7TF.getText());
            nilai8 = hitungNxK(nilai8TF.getText(), sks8TF.getText());
            nilai9 = hitungNxK(nilai9TF.getText(), sks9TF.getText());
            
            totnk = (nilai1+nilai2+nilai3+nilai4+nilai5+nilai6+nilai7+nilai8+nilai9);
            hasilnk = (totnk);
            String format = String.format("%.2f", hasilnk);
            hasilnk = Double.parseDouble(format);
        }catch (NumberFormatException e){
        }
        return hasilnk;
    }
    
     public double  hitungSKS(){
        double jumlahsks = 0, totsks;
        double  sks1, sks2, sks3, sks4, sks5, sks6, sks7, sks8, sks9;
        try{
            sks1 = getSKS(sks1TF.getText());
            sks2 = getSKS(sks2TF.getText());
            sks3 = getSKS(sks3TF.getText());
            sks4 = getSKS(sks4TF.getText());
            sks5 = getSKS(sks5TF.getText());
            sks6 = getSKS(sks6TF.getText());
            sks7 = getSKS(sks7TF.getText());
            sks8 = getSKS(sks8TF.getText());
            sks9 = getSKS(sks9TF.getText());
            
            totsks = (sks1+sks2+sks3+sks4+sks5+sks6+sks7+sks8+sks9);
            
            jumlahsks = (totsks);
            String format = String.format("%.2f", jumlahsks);
            jumlahsks = Double.parseDouble(format);
        }catch (NumberFormatException e){
        }
        return jumlahsks;
    }
    
    public String setNK(String a, String b){
        String valueOf = String.valueOf(hitungNxK(a,b));
        return valueOf;
    }
    public String setToString(Object object){
        String valueOf = String.valueOf(object);
        return valueOf;
    }
    public void show(String smester, String t_nilai){
        try {
            Statement st = koneksi.createStatement();
            String quary;
            ResultSet rs;
            
            quary = "SELECT * FROM "+smester+" where kd_matkul =1";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk1.setText(matkul);
                nilai1TF.setText(nilai);
                sks1TF.setText(sk);
                nk1.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =2";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk2.setText(matkul);
                nilai2TF.setText(nilai);
                sks2TF.setText(sk);
                nk2.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =3";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk3.setText(matkul);
                nilai3TF.setText(nilai);
                sks3TF.setText(sk);
                nk3.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =4";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk4.setText(matkul);
                nilai4TF.setText(nilai);
                sks4TF.setText(sk);
                nk4.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =5";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk5.setText(matkul);
                nilai5TF.setText(nilai);
                sks5TF.setText(sk);
                nk5.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =6";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk6.setText(matkul);
                nilai6TF.setText(nilai);
                sks6TF.setText(sk);
                nk6.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =7";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk7.setText(matkul);
                nilai7TF.setText(nilai);
                sks7TF.setText(sk);
                nk7.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =8";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk8.setText(matkul);
                nilai8TF.setText(nilai);
                sks8TF.setText(sk);
                nk8.setText(nxk);
            }
            quary = "SELECT * FROM "+smester+" where kd_matkul =9";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String matkul = rs.getString("matkul");
                String sk = rs.getString("sks");
                String nilai = rs.getString("nilai");
                String nxk = rs.getString("nxk");
                mk9.setText(matkul);
                nilai9TF.setText(nilai);
                sks9TF.setText(sk);
                nk9.setText(nxk);
            }
            quary = "SELECT * FROM "+t_nilai+";";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String ju_sks = rs.getString("ju_sks");
                String jum_nxk = rs.getString("jum_nxk");
                String ip = rs.getString("ips");
                String ik = rs.getString("ipk");
                sks.setText(ju_sks);
                nk.setText(jum_nxk);
                ips.setText(ip);
                ipk.setText(ik);
            }
        }catch (SQLException ex) {
        }
    }
    
    public String show(String t_nilai){
        try {
            Statement st = koneksi.createStatement();
            String quary;
            ResultSet rs;
            
            quary = "SELECT * FROM "+t_nilai+";";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String ju_sks = rs.getString("ju_sks");
//                String jum_nxk = rs.getString("jum_nxk");
               return ju_sks;
            }
        }catch (SQLException ex) {
        }
        return t_nilai;    
    }
    
    public String show2(String t_nilai){
        try {
            Statement st = koneksi.createStatement();
            String quary;
            ResultSet rs;
            
            quary = "SELECT * FROM "+t_nilai+";";
            rs = st.executeQuery(quary);
            while(rs.next()){
                String jum_nxk = rs.getString("jum_nxk");
                return jum_nxk;
            }
        }catch (SQLException ex) {
        }
        return t_nilai;    
    }
    
    public void total(){
        double a,b,c,d,e,f,g,h,i,a1,b1,c1,d1,e1,f1,g1,h1,i1,ipkhasil;
        a = Integer.parseInt(show2("t_nilai1"));
        b = Integer.parseInt(show2("t_nilai2"));
        c = Integer.parseInt(show2("t_nilai3"));
        d = Integer.parseInt(show2("t_nilai4"));
        e = Integer.parseInt(show2("t_nilai5"));
        f = Integer.parseInt(show2("t_nilai6"));
        g = Integer.parseInt(show2("t_nilai7"));
        h = Integer.parseInt(show2("t_nilai8"));
        
        a1 = Integer.parseInt(show("t_nilai1"));
        b1 = Integer.parseInt(show("t_nilai2"));
        c1 = Integer.parseInt(show("t_nilai3"));
        d1 = Integer.parseInt(show("t_nilai4"));
        e1 = Integer.parseInt(show("t_nilai5"));
        f1 = Integer.parseInt(show("t_nilai6"));
        g1 = Integer.parseInt(show("t_nilai7"));
        h1 = Integer.parseInt(show("t_nilai8"));
        
        i = (a+b+c+d+e+f+g+h);
        i1 = (a1+b1+c1+d1+e1+f1+g1+h1);
        ipkhasil = (i/i1);
        ipk.setText(String.valueOf(ipkhasil));
    }
    private void warna(JLabel l, int r, int g, int b){
            l.setBackground(new Color(r,g,b));
    }

    private void hitung() {
        nk.setText(setToString(hitungNK()));
        sks.setText(setToString(hitungSKS()));
        ips.setText(setToString(hitungNK()/hitungSKS()));
        ipk.setText(String.valueOf(ipk()));
    }
    private double ipk(){
        try {
            st = koneksi.createStatement();
            String quary;
            
            quary = "SELECT * FROM `t_nilai1` AS n1 INNER JOIN t_nilai2 AS n2 INNER JOIN t_nilai3 AS n3 INNER JOIN t_nilai4 AS n4 INNER JOIN t_nilai5 AS n5 INNER JOIN t_nilai6 AS n6 INNER JOIN t_nilai7 AS n7 INNER JOIN t_nilai8 AS n8 ON n1.kd = n2.kd = n3.kd = n4.kd = n5.kd = n6.kd =  n7.kd = n8.kd ";
            rs = st.executeQuery(quary);
            while(rs.next()){
                int ju_sks1 = rs.getInt("n1.ju_sks");
                int ju_sks2 = rs.getInt("n2.ju_sks");
                int ju_sks3 = rs.getInt("n3.ju_sks");
                int ju_sks4 = rs.getInt("n4.ju_sks");
                int ju_sks5 = rs.getInt("n5.ju_sks");
                int ju_sks6 = rs.getInt("n6.ju_sks");
                int ju_sks7 = rs.getInt("n7.ju_sks");
                int ju_sks8 = rs.getInt("n8.ju_sks");
                
                double jum_nxk1 = rs.getDouble("n1.jum_nxk");
                double jum_nxk2 = rs.getDouble("n2.jum_nxk");
                double jum_nxk3 = rs.getDouble("n3.jum_nxk");
                double jum_nxk4 = rs.getDouble("n4.jum_nxk");
                double jum_nxk5 = rs.getDouble("n5.jum_nxk");
                double jum_nxk6 = rs.getDouble("n6.jum_nxk");
                double jum_nxk7 = rs.getDouble("n7.jum_nxk");
                double jum_nxk8 = rs.getDouble("n8.jum_nxk");
                
                double jumNxK = (jum_nxk1+jum_nxk2+jum_nxk3+jum_nxk4+jum_nxk5+jum_nxk6+jum_nxk7+jum_nxk8);
                int jumSKS = (ju_sks1+ju_sks2+ju_sks3+ju_sks4+ju_sks5+ju_sks6+ju_sks7+ju_sks8);
                double Ipk = (jumNxK/jumSKS);
                return Ipk;
            }
        } catch (SQLException e) {
        }
        return 0;
    }
}
